### ISSUE TITLE
Alluxio CLI and start/stop scripts in golang

### ISSUE THREAD

**Issue by Xenorith** [Alluxio/alluxio#17522]
This issue tracks the effort started in https://github.com/Alluxio/alluxio/pull/17463

# TODO list
- [ ] Incorporate CLI commands defined in https://github.com/Alluxio/alluxio/blob/main/dora/integration/fuse/bin/alluxio-fuse (from @LuQQiu in https://github.com/Alluxio/alluxio/pull/17463#pullrequestreview-1437635768)
- [ ] Handle expected user errors more gracefully, hiding the stacktrace by default (from @ssz1997 in https://github.com/Alluxio/alluxio/pull/17463#issuecomment-1561770422)
- [x] Define guidelines for the CLI command layout as inspired by https://primer.style/design/native/cli/foundations (from @jenoudet in https://github.com/Alluxio/alluxio/pull/17463#discussion_r1210786922)
- [ ] Use process registry to produce entrypoint for docker image, started in https://github.com/Alluxio/alluxio/pull/17597
- [x] Add tarball generation logic into build workflow
  - [x] Handle changing the assembly jar path when the jars are reorganized within a tarball
  - [x] Omit line in `bin/cli.sh` that builds the CLI
- [ ] Incorporate validation via struct field annotations as descsribed in https://github.com/Alluxio/alluxio/pull/17570#discussion_r1222257777
- [x] (nice to have) Mechanism to generate CLI documentation from golang code
- [ ] (nice to have) Generate alluxio-env.sh.template and validate in PR check that it is up to date

# Background
The CLI in the bash format has grown to be a giant monolith of bash code. One of the goals in the new `main` branch is to properly modularize various portions of the codebase and the set of bash scripts within the `bin/` folder is one obvious counterexample to this goal.
## Advantages:
- Writing in a more structured language other than bash will prevent mistakes such as https://github.com/Alluxio/alluxio/pull/17459
- Golang can be compiled into an executable binary such that there are no additional runtime requirements for Alluxio, as opposed to using an interpreted language such as python
## Disadvantages
- Introduces golang as a new compilation/development requirement, which was previously a soft requirement as it was needed to run certain scripts such as building the tarball
- Compiled executables delivered as part of the tarball cannot be edited, unlike the bash scripts

# Layout/Implementation
- All cli go code are in the `cli/` directory.
  - If the `-PgoCli` flag is added when running maven, it will build the required go binary to execute.
  - If running the `bin/cli.sh` command and the go binary isn't built yet, it will build on demand
  - Otherwise, the go cli will not be built. This prevents golang to be a must-have requirement for building the project; will translate it to be a default after deprecating the existing bash cli.
- The user provided environment variables remains the same as before, via setting in `conf/alluxio-env.sh`.
- The environment variables are managed by [viper](https://github.com/spf13/viper)
  -  `InitAlluxioEnv()` in `cli/env/env.go` initializes the default values and reading from the above user config file, storing them in a global `env.Env` variable; effectively replacing `libexec/alluxio-config.sh`
  - Unlike in bash where variable substitution is rampant, all variables values are always stored in their fully expanded form
- The CLI command tree is managed by [cobra](https://github.com/spf13/cobra)
  - Logging with log levels is enabled by [logrus](https://github.com/sirupsen/logrus)
  - Adding `--debugLog` enables verbose logging to diagnose the logic flow and when appropriate, prints out the corresponding and fully expanded bash command 
- The `Process` interface outlines the definition of an Alluxio process
  - The process defines its own environment variables and sets them in `env.Env` for subsequent logic to access
  - The process is added to the command tree under the `process` subcommand, where currently the only actionable command is `Start()`
  - The only current process defined is the `Master` process in `cli/process/master.go`
- The `Command` interface outlines the definition for running a java class
  - The command is added to the command tree under the root command, but could easily expand into its own subcommand tree following cobra's conventions
  - The `BaseCommand` struct is designated to be embedded in full implementations of the command interface
    - `BaseCommand.RunJavaClassCmd()` organizes the environment variables, java opts, and command line arguments, effectively replacing `function runJavaClass` in `bin/alluxio`
- Processes and commands are registered in `cli/main.go`, the entrypoint go file that is compiled to a binary.
  - Combined with the process and command interfaces, this code architecture promotes extensibility, allowing another go project to use this code as a dependency, picking which processes and commands to register as they choose.

**Comment by Kai-Zhang** [comment]
can we name the new client "alluxio" or something similar?
i used to add the alluxio `bin/` directory to my `PATH` so i can run command like `alluxio fs ls` without entering certain directories or specifying a very long path. but if i do the same thing with the new cli, the `cli.sh formatJournal` would be a little bit confusing since there's no "alluxio" in it. also a clear name helps if i didn't put the artifacts in a path named "alluxio".

**Comment by Xenorith** [comment]
> can we name the new client "alluxio" or something similar?

i may need to keep the existing `bin/alluxio` even after the new CLI is merged. any recommendation for another name to prevent collision?

**Comment by Kai-Zhang** [comment]
i think "alluxio-cli" could work but the suffix seems redundant.
not sure if we need to honor the users' custom. i think we can add some simple multiplex logic in `bin/alluxio` and route all the subcommands to the new golang cli binary except some leftover subcommands, which we could re-routine to the legacy `bin/alluxio` script. in this case, the legacy script could be renamed as `bin/alluxio-legacy` or `bin/alluxio-internal` or something else.

**Comment by Xenorith** [comment]
> the GitHub cli is `gh`, maybe we can use a diminutive in the same manner, like `ax` or `alx`.

`alx` seems good to me though it might take some explaining and time to get used to. i will also consider the backcompat of the existing `alluxio` script and fork it between the new vs old versions

**Comment by Xenorith** [comment]
consider this issue mostly complete, many improvements still to come
